services:
  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
      args:
        DB_DATABASE: ${DB_DATABASE:-database}
        DB_USER: ${DB_USER:-user}
        DB_PORT: ${DB_PORT:-3306}
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-database}
      MYSQL_USER: ${DB_USER:-user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
      MYSQL_TCP_PORT: ${DB_PORT:-3306}
    ports:
      - "${DB_PORT:-3306}:${DB_PORT:-3306}"
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    command: --mysql-native-password=ON
    networks:
      - candyshop

volumes:
  db_data:
    driver: local

networks:
  candyshop:
    driver: bridge